name: Rebase main ontop upstream-develop
on:
  workflow_dispatch:
  push:
    branches:
      - upstream-develop

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Try rebase
      run: |
        set -euxo pipefail
        git config --global user.name "GitHub Actions"
        git config --global user.email "githubactions@github.com"

        git rebase upstream-develop
        git push origin HEAD:main --force-with-lease
